### ISSUE TITLE
Models Did not Show Up in Workspace

### ISSUE THREAD

**Issue by yilinxia** [cropsinsilico/jupyterlab_nodeeditor#32]
with creating the editor and the socket_types

```
schema = yamlfile.get_schema()
socket_types = tuple(schema.form_schema['definitions']['schema']['definitions']['simpleTypes']['enum'])
coll = jlne.SocketCollection(socket_types = socket_types
editor = jlne.NodeEditor(socket_collection=coll)
editor
```
we start to build the instance with `jlne.node_editor.NodeInstanceModel`
```
in1 = jlne.InputSlot(title = "inputA", key = "in_1", sockets = coll,  multi_connection=True)
out1 = jlne.OutputSlot(title = "outputA", key = "out_1", sockets = coll,multi_connection=True)
contrl1=jlne.TextInputControlModel(key = 'my_key', editor = editor.node_editor, initial_value="./src/gs_lesson4_modelA.py")
in2 = jlne.InputSlot(title = "inputB", key = "in_1", sockets = coll,  multi_connection=True)
out2 = jlne.OutputSlot(title = "outputB", key = "out_1", sockets = coll,multi_connection=True)
contrl2=jlne.TextInputControlModel(key = 'my_key', editor = editor.node_editor, initial_value="./src/gs_lesson4_modelB.py")

new_node1=jlne.node_editor.NodeInstanceModel(title="ModelA",inputs=[in1], outputs=[out1], controls=[contrl1])
new_node2=jlne.node_editor.NodeInstanceModel(title="ModelB",inputs=[in2], outputs=[out2], controls=[contrl2])

editor.node_editor.nodes=editor.node_editor.nodes+[new_node1,new_node2]
```
which supposed to be show up in the interface but it did not

<img width="978" alt="image" src="https://user-images.githubusercontent.com/24869900/211093150-8ec5fab7-35a9-4f5e-bfc2-8f632755bc96.png">

**Comment by matthewturk** [comment]
@yilinxia Does this only happen on your branch with the yaml file loading?  If not, can you provide an example that demonstrates it on the main branch?

**Comment by yilinxia** [comment]
@matthewturk hi matt, I have revised the code above. Sorry for the inconvenience

**Comment by matthewturk** [comment]
Thanks!  I'm able to replicate.

**Comment by matthewturk** [comment]
This seems to be the error:

```
595.e3c9c115ecf5763f080b.js?v=e3c9c115ecf5763f080b:1 Error: Could not process update msg for model id: d1efca2298b741b5853aa34b1d1177d4
    at 595.e3c9c115ecf5763f080b.js?v=e3c9c115ecf5763f080b:1:1356
    at async b._handleCommMsg (jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2:1001813)
    at async b._handleMessage (jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2:1003397)
(anonymous) @ 595.e3c9c115ecf5763f080b.js?v=e3c9c115ecf5763f080b:1
jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2 Connection lost, reconnecting in 0 seconds.
_reconnect @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1 Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm was closed too early
_loadFromKernel @ 150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1
rete.esm.js:1524 Uncaught (in promise) Error: Component ModelA not found
    at EditorView.addNode (rete.esm.js:1524:1)
    at NodeEditor.addNode (rete.esm.js:1759:1)
    at ReteEditorView.updateNodes (widget.js:361:1)
    at v (644.11f638668109f1562dd1.js?v=11f638668109f1562dd1:1:3143)
    at d (644.11f638668109f1562dd1.js?v=11f638668109f1562dd1:1:2817)
    at c (644.11f638668109f1562dd1.js?v=11f638668109f1562dd1:1:740)
    at a.trigger (644.11f638668109f1562dd1.js?v=11f638668109f1562dd1:1:2710)
    at ReteEditorModel.f (595.e3c9c115ecf5763f080b.js?v=e3c9c115ecf5763f080b:1:4257)
    at ReteEditorModel.set (595.e3c9c115ecf5763f080b.js?v=e3c9c115ecf5763f080b:1:9550)
    at ReteEditorModel.set_state (595.e3c9c115ecf5763f080b.js?v=e3c9c115ecf5763f080b:1:8656)
595.e3c9c115ecf5763f080b.js?v=e3c9c115ecf5763f080b:1 Error: Could not process update msg for model id: 189d5c85d08a43da95996023d9491cd3
    at 595.e3c9c115ecf5763f080b.js?v=e3c9c115ecf5763f080b:1:1356
    at async b._handleCommMsg (jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2:1001813)
    at async b._handleMessage (jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2:1003397)
(anonymous) @ 595.e3c9c115ecf5763f080b.js?v=e3c9c115ecf5763f080b:1
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/main.4d34365dd4c9118d37aa.js.map?v=4d34365dd4c9118d37aa: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/5096.96faf5ddac346a9ad9c3.js.map?v=96faf5ddac346a9ad9c3: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/6700.c96344a466d1896657bf.js.map?v=c96344a466d1896657bf: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/4155.784ca1752696680bf373.js.map?v=784ca1752696680bf373: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/1033.890eeae47460e241b1e9.js.map?v=890eeae47460e241b1e9: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/7294.f71c2889fedcd71bd1ee.js.map?v=f71c2889fedcd71bd1ee: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/4570.53adcb6f69939da383ff.js.map?v=53adcb6f69939da383ff: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/2719.3fe9e6fa24f270d8b8d1.js.map?v=3fe9e6fa24f270d8b8d1: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/1036.a055f7326513fc5a04f7.js.map?v=a055f7326513fc5a04f7: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/1142.074d125bb59f5a332666.js.map?v=074d125bb59f5a332666: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/9473.2e52d2ba788beec303be.js.map?v=2e52d2ba788beec303be: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/3935.4159b022aa6d82e44127.js.map?v=4159b022aa6d82e44127: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/2040.6489997c35a5d7b0b100.js.map?v=6489997c35a5d7b0b100: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/3029.8636761a48c8422ce37f.js.map?v=8636761a48c8422ce37f: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/1057.a0608544097dd22a589e.js.map?v=a0608544097dd22a589e: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/283.4051a0b7d358b17d0580.js.map?v=4051a0b7d358b17d0580: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/4151.fd7ca59b64f0adc97032.js.map?v=fd7ca59b64f0adc97032: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/911.0c08f040896753efc653.js.map?v=0c08f040896753efc653: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/4429.c4f083ef6b6e29345fd4.js.map?v=c4f083ef6b6e29345fd4: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/1358.9ab4f57e8227ce75f427.js.map?v=9ab4f57e8227ce75f427: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/1249.047c76b5ea96a41605db.js.map?v=047c76b5ea96a41605db: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/3496.ecb0e7fcc54191234ae6.js.map?v=ecb0e7fcc54191234ae6: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/466.239a0c009f33f1cb7cab.js.map?v=239a0c009f33f1cb7cab: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/3502.c915d993b864739407e3.js.map?v=c915d993b864739407e3: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/807.96166378e2efe232d81e.js.map?v=96166378e2efe232d81e: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/126.1e2fb998804b27c72a3e.js.map?v=1e2fb998804b27c72a3e: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/jlab_core.4566032f8b9a1bbebc97.js.map?v=4566032f8b9a1bbebc97: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/6080.39703b8cc7bd284ce1bd.js.map?v=39703b8cc7bd284ce1bd: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/7796.1c32d8a9d4009b8f985d.js.map?v=1c32d8a9d4009b8f985d: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/7755.d506a1d9dadf30b1e490.js.map?v=d506a1d9dadf30b1e490: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/3308.3a94151c0d57440646ab.js.map?v=3a94151c0d57440646ab: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/4631.96a143e70f005fef7b59.js.map?v=96a143e70f005fef7b59: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:8888/static/lab/714.ff3007d0b781b5538482.js.map?v=ff3007d0b781b5538482: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not parse content for http://localhost:8888/lab/tree/Menu.vue.map: Unexpected token '<', "<!doctype "... is not valid JSON
DevTools failed to load source map: Could not parse content for http://localhost:8888/lab/tree/Item.vue.map: Unexpected token '<', "<!doctype "... is not valid JSON
DevTools failed to load source map: Could not parse content for http://localhost:8888/lab/tree/Search.vue.map: Unexpected token '<', "<!doctype "... is not valid JSON
jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2 Connection lost, reconnecting in 0 seconds.
_reconnect @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
reconnect @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
restart @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
await in restart (async)
restartKernel @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
restart @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
await in restart (async)
restartKernelAndClear @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
(anonymous) @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
e.execute @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
t.triggerActiveItem @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
t._evtMouseUp @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
t.handleEvent @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
jlne_issue32.ipynb:1 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1 Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm was closed too early
_loadFromKernel @ 150.b0e841b75317744a7595.js?v=b0e841b75317744a7595:1
await in _loadFromKernel (async)
_loadFromKernel @ 134.40eaa5b8e976096d50b2.js?v=40eaa5b8e976096d50b2:1
restoreWidgets @ 134.40eaa5b8e976096d50b2.js?v=40eaa5b8e976096d50b2:1
_handleKernelConnectionStatusChange @ 134.40eaa5b8e976096d50b2.js?v=40eaa5b8e976096d50b2:1
(anonymous) @ 134.40eaa5b8e976096d50b2.js?v=40eaa5b8e976096d50b2:1
m @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
l @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
e.emit @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
_onConnectionStatusChanged @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
m @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
l @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
e.emit @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
onKernelConnectionStatus @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
m @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
l @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
e.emit @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
_updateConnectionStatus @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
_onWSOpen @ jlab_core.4566032f8b9a1bbebc97.js?v=4566032f8b9a1bbebc97:2
rete.esm.js:1524 Uncaught (in promise) Error: Component ModelA not found
    at EditorView.addNode (rete.esm.js:1524:1)
    at NodeEditor.addNode (rete.esm.js:1759:1)
    at ReteEditorView.updateNodes (widget.js:361:1)
    at v (644.11f638668109f1562dd1.js?v=11f638668109f1562dd1:1:3143)
    at d (644.11f638668109f1562dd1.js?v=11f638668109f1562dd1:1:2817)
    at c (644.11f638668109f1562dd1.js?v=11f638668109f1562dd1:1:740)
    at a.trigger (644.11f638668109f1562dd1.js?v=11f638668109f1562dd1:1:2710)
    at ReteEditorModel.f (595.e3c9c115ecf5763f080b.js?v=e3c9c115ecf5763f080b:1:4257)
    at ReteEditorModel.set (595.e3c9c115ecf5763f080b.js?v=e3c9c115ecf5763f080b:1:9550)
    at ReteEditorModel.set_state (595.e3c9c115ecf5763f080b.js?v=e3c9c115ecf5763f080b:1:8656)
```

**Comment by matthewturk** [comment]
So what I think is happening is that Rete expects that each node instance will be tied to a type of component it knows about.  I'm trying to dig deeper in.
